title = "Alpaca Kaukoputki (Telescope)"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6
serial_port = '/dev/ttyACM0'

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
